import { defineConfig } from 'vitest/config';
import path from 'node:path';

export default defineConfig({
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      '~': path.resolve(__dirname, './'),
    },
  },
  test: {
    environment: 'happy-dom',
    globals: true,
    include: ['src/**/*.test.{ts,tsx}', 'tests/*.test.{ts,tsx}'],
    exclude: [
      'node_modules/**',
      'dist/**',
      'coverage/**',
      'tests/unit/**',
    ],
    css: true,
    mockReset: true,
    restoreMocks: true,
    clearMocks: true,
    testTimeout: 10000,
    hookTimeout: 10000,
    isolate: true,
    setupFiles: [],

    coverage: {
      provider: 'v8',
      reporter: ['text', 'text-summary'],
      include: [
        'src/adapters/**/*.{ts,tsx}',
        'src/store/**/*.{ts,tsx}',
        'src/config/**/*.{ts,tsx}',
        'src/core/**/*.{ts,tsx}',
        'src/services/broadcastSyncService.ts',
        'src/utils/p0FrozenCoreGuard.ts',
        'src/utils/telemetry.ts',
        'src/utils/telemetrySnapshot.ts',
        'src/utils/alertEngine.ts',
        'src/utils/toast.ts',
        'src/utils/vibration.ts',
        'src/utils/clipboard.ts',
      ],
      exclude: [
        'src/**/*.d.ts',
        'src/**/*.stories.{ts,tsx}',
        'src/**/index.ts',
        'src/data/**',
        'src/components/forensics/**',
        'src/utils/*Pdf*.ts',
        'src/utils/*Export*.ts',
        'src/utils/forensic*.ts',
        'src/utils/court*.ts',
        'src/utils/evidence*.ts',
        'src/utils/masterForensicAuditPackage.ts',
        'src/utils/p1QuarantineLayer.ts',
        'src/utils/p2ForensicEngine.ts',
        'src/utils/p3ArtifactEngine.ts',
        'src/utils/phase21_30Engine.ts',
        'src/utils/phase31_40Engine.ts',
        'src/services/CourtEvidenceDossierGenerator.ts',
        'src/services/EvidenceExportService.ts',
        'src/services/LegalPrintAutomation.ts',
      ],
    },
  },
});
