apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "senate-gate.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "senate-gate.name" . }}
    helm.sh/chart: {{ include "senate-gate.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    zyrquen.network/tier: {{ .Values.global.tier | default "sovereign-enterprise" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "senate-gate.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        app.kubernetes.io/name: {{ include "senate-gate.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: senate-gate
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ENGINE_MODE
              value: {{ .Values.engine.mode | quote }}
            - name: SHORT_CIRCUIT_ENABLED
              value: {{ .Values.engine.shortCircuitEnabled | quote }}
            - name: GEO_REGION
              value: {{ .Values.global.geoRegion | quote }}
            - name: CLUSTER_ID
              value: {{ .Values.global.clusterId | quote }}
          ports:
            - name: http
              containerPort: 8181
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
