{
  "name": "zyrquen-sovereign-kernel",
  "private": true,
  "version": "1.2.0-LTS",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview",
    "test": "vitest run"
  },
  "dependencies": {
    "express": "^4.19.2",
    "framer-motion": "^11.5.4",
    "jsqr": "^1.4.0",
    "lucide-react": "^0.439.0",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "three": "^0.168.0"
  },
  "devDependencies": {
    "@types/express": "^4.17.21",
    "@types/node": "^22.5.4",
    "@types/react": "^18.3.5",
    "@types/react-dom": "^18.3.0",
    "@types/three": "^0.168.0",
    "@typescript-eslint/eslint-plugin": "^8.4.0",
    "@typescript-eslint/parser": "^8.4.0",
    "@vitejs/plugin-react": "^4.3.1",
    "autoprefixer": "^10.4.20",
    "eslint": "^9.9.1",
    "postcss": "^8.4.45",
    "tailwindcss": "^3.4.10",
    "typescript": "~5.6.2",
    "vite": "^5.4.3",
    "vitest": "^2.0.5"
  }
}
